# Generated by Django 6.0.3 on 2026-04-16 11:58

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('directeur', 'Directeur'), ('directeur_region', 'Directeur de Région'), ('responsable_structure', 'Responsable de Structure'), ('divisionnaire', 'Divisionnaire'), ('agent', 'Agent')], max_length=30)),
                ('photo_profil', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('matricule', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('poste', models.CharField(blank=True, max_length=100, null=True)),
                ('region_id', models.CharField(blank=True, max_length=24, null=True)),
                ('structure_id', models.CharField(blank=True, max_length=24, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('chef', models.ForeignKey(blank=True, help_text='Le chef auquel cet agent est affecté', limit_choices_to={'role': 'chef'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_agents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text="L'utilisateur qui a le rôle agent", on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
    ]
