# Generated by Django 6.0.3 on 2026-04-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('chef', 'Chef'), ('directeur', 'Directeur'), ('directeur_region', 'Directeur de Région'), ('responsable_structure', 'Responsable de Structure'), ('divisionnaire', 'Divisionnaire'), ('agent', 'Agent')], max_length=30, null=True),
        ),
    ]
