# Generated by Django 5.2.12 on 2026-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='annee_debut_projet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='mois_debut_projet',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
