# Generated by Django 6.0.3 on 2026-05-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_reserve_directeur_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_reserve_directeur_region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_reserve_directeur_direction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_reserve_directeur_region',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='reserve_par_directeur_direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='reserve_par_directeur_region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='budgetrecord',
            name='statut_final',
            field=models.CharField(blank=True, choices=[('valide_divisionnaire', 'Validé Divisionnaire'), ('rejete_divisionnaire', 'Rejeté Divisionnaire'), ('annule_divisionnaire', 'Annulé Divisionnaire'), ('valide_directeur_region', 'Validé Directeur Région'), ('rejete_directeur_region', 'Rejeté Directeur Région'), ('reserve_directeur_region', 'Réservé Directeur Région'), ('valide_directeur_direction', 'Validé Directeur Direction'), ('rejete_directeur_direction', 'Rejeté Directeur Direction'), ('reserve_directeur_direction', 'Réservé Directeur Direction')], help_text='Statut final après décision terminale', max_length=30, null=True),
        ),
    ]
