# Generated by Django 6.0.3 on 2026-04-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetrecord',
            name='region',
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='departement_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='direction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='region_direction',
            field=models.CharField(blank=True, help_text='code_region si structure | code_direction si département', max_length=50, null=True),
        ),
    ]
