# Generated by Django 6.0.3 on 2026-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetrecord',
            options={'ordering': ['-version']},
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='parent_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='version_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='budgetrecord',
            unique_together={('code_division', 'version')},
        ),
    ]
