# Generated by Django 6.0.3 on 2026-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0002_remove_budgetrecord_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetrecord',
            name='region_direction',
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='direction',
            field=models.CharField(blank=True, help_text='Code direction — responsable_departement uniquement', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='region',
            field=models.CharField(blank=True, help_text='Code région — responsable_structure uniquement', max_length=50, null=True),
        ),
    ]
