# Generated by Django 6.0.3 on 2026-04-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0002_alter_budgetrecord_options_budgetrecord_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetrecord',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='budgetrecord',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='budgetrecord',
            index=models.Index(fields=['code_division', 'version'], name='idx_code_division_version'),
        ),
        migrations.AddIndex(
            model_name='budgetrecord',
            index=models.Index(fields=['code_division', 'is_active'], name='idx_code_division_active'),
        ),
    ]
