# Generated by Django 6.0.3 on 2026-04-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0003_alter_budgetrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrecord',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('soumis', 'Soumis'), ('valide_directeur_region', 'Validé Directeur Région'), ('rejete', 'Rejeté'), ('valide_agent', 'Validé Agent'), ('reserve_agent', 'Réservé Agent'), ('valide_chef', 'Validé Chef'), ('reserve_chef', 'Réservé Chef'), ('valide_directeur', 'Validé Directeur'), ('reserve_directeur', 'Réservé Directeur'), ('valide_divisionnaire', 'Validé Divisionnaire')], default='brouillon', max_length=50),
        ),
    ]
