# Generated by Django 6.0.3 on 2026-04-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0003_remove_budgetrecord_region_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_point_situation',
            field=models.TextField(blank=True, help_text='Commentaire sur le point de situation', null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_maj_point_situation',
            field=models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour du point de situation', null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='duree_realisation',
            field=models.IntegerField(blank=True, help_text='Durée de réalisation du projet en mois (ex: 36)', null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='point_situation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Point de situation du projet en pourcentage (ex: 75.50)', max_digits=5, null=True),
        ),
    ]
