# Generated by Django 6.0.3 on 2026-04-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0004_budgetrecord_commentaire_point_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrecord',
            name='point_situation',
            field=models.TextField(blank=True, help_text='Point de situation du projet en pourcentage (ex: 75.50)', null=True),
        ),
    ]
