# Generated by Django 6.0.3 on 2026-04-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0004_alter_budgetrecord_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
