# Generated by Django 6.0.3 on 2026-04-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_recap', '0005_alter_budgetrecord_point_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecord',
            name='commentaire_directeur_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_rejet_directeur_direction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='date_validation_directeur_direction',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='motif_rejet_directeur_direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='rejete_par_directeur_direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budgetrecord',
            name='valide_par_directeur_direction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='budgetrecord',
            name='statut_final',
            field=models.CharField(blank=True, choices=[('valide_divisionnaire', 'Validé Divisionnaire'), ('rejete_divisionnaire', 'Rejeté Divisionnaire'), ('annule_divisionnaire', 'Annulé Divisionnaire'), ('valide_directeur_region', 'Validé Directeur Région'), ('rejete_directeur_region', 'Rejeté Directeur Région'), ('valide_directeur_direction', 'Validé Directeur Direction'), ('rejete_directeur_direction', 'Rejeté Directeur Direction')], help_text='Statut final après décision terminale', max_length=30, null=True),
        ),
    ]
